title: Machine Learning for Natural Language Processing

description: Class on machine learning for natural language processing at YSU-ISTC Machine Learning Summer School

logo: https://deeplanguageclass.github.io/favicon.ico
